# Schema for the configuration files of the Crossref API Client module.
crossref_api_client.settings:
  type: config_object
  label: 'Crossref API Client settings'
  mapping:
    email:
      type: email
      label: 'Contact Email'
    token:
      type: string
      label: 'Plus service API token'
    debug:
      type: boolean
      label: 'Log debugging info'

